name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ii -ll -r . -f json -o bandit-report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json

  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Set up Docker Daemon
        run: |
          sudo mkdir -p /etc/docker
          echo '{"insecure-registries":["myregistry.com"]}' | sudo tee /etc/docker/daemon.json

      - name: Docker Scout Scan
        run: |
          # Install Docker Scout CLI
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

          # Log in to Docker registry
          echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin

          # Perform a scan of the Docker image
          docker scout quickview myapp:latest
          docker scout cves myapp:latest
